name: gitStream and ESLint Checks

permissions:
  contents: read
  pull-requests: write
  statuses: write

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      client_payload:
        description: 'The Client payload'
        required: true
      full_repository:
        description: 'The repository name including the owner in owner/repo_name format'
        required: true
      head_ref:
        description: 'The head sha'
        required: true
      base_ref:
        description: 'The base ref'
        required: true
      installation_id:
        description: 'The installation id'
        required: false
      resolver_url:
        description: 'The resolver url to pass results to'
        required: true
      resolver_token:
        description: 'Optional resolver token for resolver service'
        required: false
        default: ""

jobs:
  gitStream:
    runs-on: ubuntu-latest
    name: gitStream workflow automation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full repository history

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci

      # Add a step to check if gitstream.cm exists
      - name: Validate gitstream.cm presence
        run: |
          if [ ! -f ./gitstream.cm ]; then
            echo "gitstream.cm not found at the root of the repository!"
            exit 1
          else
            echo "gitstream.cm file found."
          fi

      - name: Validate and Set GitStream Inputs
        id: set-inputs
        run: |
          full_repo="${{ github.event.inputs.full_repository || github.repository }}"
          head_ref="${{ github.event.inputs.head_ref || github.head_ref }}"
          base_ref="${{ github.event.inputs.base_ref || github.base_ref }}"
          client_payload='${{ github.event.inputs.client_payload || '{}' }}'
          
          if [ -z "$full_repo" ] || [ -z "$head_ref" ] || [ -z "$base_ref" ]; then
            echo "Missing required inputs!"
            echo "full_repository: $full_repo"
            echo "head_ref: $head_ref"
            echo "base_ref: $base_ref"
            exit 1
          fi
          
          echo "All required inputs are present."
          echo "full_repository=$full_repo" >> $GITHUB_OUTPUT
          echo "head_ref=$head_ref" >> $GITHUB_OUTPUT
          echo "base_ref=$base_ref" >> $GITHUB_OUTPUT
          echo "client_payload=$client_payload" >> $GITHUB_OUTPUT
      
      - name: Evaluate GitStream Rules (Ignore Errors)
        id: rules-engine
        continue-on-error: true  # Ensures that GitStream errors do not fail the job
        with:
          full_repository: ${{ github.event.inputs.full_repository || github.repository }}
          head_ref: ${{ github.event.inputs.head_ref || github.head_ref }}
          base_ref: ${{ github.event.inputs.base_ref || github.base_ref }}
          client_payload: ${{ github.event.inputs.client_payload || '{}' }}  # Ensure valid JSON
          installation_id: ${{ github.event.inputs.installation_id }}
          resolver_url: ${{ github.event.inputs.resolver_url }}
          resolver_token: ${{ github.event.inputs.resolver_token || secrets.RESOLVER_TOKEN }}
      
      - name: Debug GitStream output (Optional)
        if: always()
        run: |
          echo "GitStream status: ${{ steps.rules-engine.outputs.gitstream_status }}"
          echo "GitStream exit code: ${{ steps.rules-engine.outcome }}"

      - name: GitStream Comment on PR (Optional)
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = '${{ steps.rules-engine.outputs.gitstream_status }}';
            if (status === 'warning') {
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: 'GitStream encountered known errors but the workflow continued.'
              });
            }
  
  lint:
    runs-on: ubuntu-latest
    name: ESLint Check
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        id: eslint
        run: |
          npx eslint . --format=stylish || true
          ESLINT_EXIT_CODE=$?
          if [ $ESLINT_EXIT_CODE -eq 0 ]; then
            echo "eslint_status=success" >> $GITHUB_OUTPUT
            echo "eslint_message=ESLint check passed" >> $GITHUB_OUTPUT
          else
            echo "eslint_status=failure" >> $GITHUB_OUTPUT
            echo "eslint_message=ESLint found issues" >> $GITHUB_OUTPUT
          fi
      
      - name: Report ESLint status
        if: always()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = '${{ steps.eslint.outputs.eslint_status }}';
            const description = '${{ steps.eslint.outputs.eslint_message }}';
            
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: status,
              context: 'ESLint Check',
              description: description
            });
            
            if (status === 'failure') {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: 'ESLint check failed. Please review the workflow logs for details.'
              });
            }
