name: gitStream and ESLint Checks

on:
  pull_request:
    branches:
      - first_branch

jobs:
  eslint-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Upload ESLint results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: eslint-results
          path: eslint-results/

  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization_key
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io

  gitstream-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Debugging step for inputs
      - name: Debug Inputs
        run: |
          echo "full_repository: ${{ github.event.inputs.full_repository }}"
          echo "head_ref: ${{ github.event.inputs.head_ref }}"
          echo "base_ref: ${{ github.event.inputs.base_ref }}"

      - name: Run gitStream
        uses: linear-b/gitstream-github-action@v1
        with:
          client_payload: ${{ github.event.inputs.client_payload }}
          full_repository: ${{ github.event.inputs.full_repository }}
          head_ref: ${{ github.event.inputs.head_ref }}
          base_ref: ${{ github.event.inputs.base_ref }}

      - name: Check gitStream workflow
        run: |
          echo "Check gitStream Workflow Status"

  # Optional job to clean up if needed
  cleanup:
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Remove Artifacts
        run: rm -rf eslint-results
